WebDevelopmentExams/AspNetMVC/Exam/Exam.Web/Controllers/CategoryAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exam.Web.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

namespace Exam.Web.Controllers
{
    public class CategoryAdminController : BaseController
    {
        [Authorize(Roles = "Admin")]
        //
        // GET: /CategoryAdmin/
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ReadCommand([DataSourceRequest] DataSourceRequest request)
        {
            var model = this.Data.Categories.All().Select(CategoryViewModel.ToViewModel);
            return Json(model.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateCommand([DataSourceRequest] DataSourceRequest request, CategoryViewModel model)
        {
            var entity = this.Data.Categories.GetById(model.Id);

            entity.Name = model.Name;
            this.Data.SaveChanges();

            return Json(new[] { model }.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult DestroyCommand([DataSourceRequest] DataSourceRequest request, CategoryViewModel model)
        {
            var tickets = Data.Tickets.All().Where(x => x.CategoryId == model.Id).ToList();
            foreach (var ticket in tickets)
            {
                Data.Tickets.Delete(ticket);
            }
            this.Data.Categories.Delete(model.Id);
            this.Data.SaveChanges();

            return Json(new[] { model }.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

	}
}

WebDevelopmentExams/AspNetMVC/Exam/Exam.Web/Controllers/CommentAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Exam.Models;
using Exam.Data;

namespace Exam.Web.Controllers
{
    public class CommentAdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /CommentAdmin/
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Author).Include(c => c.Ticket);
            return View(comments.ToList());
        }

        // GET: /CommentAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: /CommentAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName", comment.AuthorId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", comment.TicketId);
            return View(comment);
        }

        // POST: /CommentAdmin/Edit/5
		// To protect from over posting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		// 
		// Example: public ActionResult Update([Bind(Include="ExampleProperty1,ExampleProperty2")] Model model)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                var entity = db.Comments.Find(comment.Id);
                if (entity != null)
                {
                    entity.Content = comment.Content;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "UserName", comment.AuthorId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", comment.TicketId);
            return View(comment);
        }

        // GET: /CommentAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: /CommentAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebDevelopmentExams/AspNetMVC/Exam/Exam.Web/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exam.Models;
using Exam.Web.Helpers;
using Exam.Web.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;

namespace Exam.Web.Controllers
{
    
    public class TicketController : BaseController
    {
        [Authorize]
        //
        // GET: /Ticket/List
        public ActionResult List()
        {
            var model = Data.Tickets.All().Select(TicketsViewModel.ToViewModel);
            return View(model);
        }

        [Authorize]
        public JsonResult GetTickets([DataSourceRequest] DataSourceRequest request)
        {
            var model = Data.Tickets.All().Select(TicketsViewModel.ToViewModel);
            return Json(model.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult Create()
        {
            CreateTicketViewModel model = new CreateTicketViewModel();
            model.CategoryItems = Data.Categories.All().ToList().Select(x => new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = x.Name
            }).ToList();

            model.PriorityItems = Enum.GetValues(typeof(PriorityType)).Cast<PriorityType>().Select(v => new SelectListItem
            {
                Text = v.ToString(),
                Value = ((int)v).ToString()
            }).ToList();

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(CreateTicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var ticket = new Ticket();
                ticket.AuthorId = userId;
                ticket.CategoryId = model.SelectedCategory;
                ticket.Title = model.Title;
                ticket.Priority = model.SelectedPriority;
                ticket.ScreenshotURL = model.ScreenshotUrl;
                ticket.Description = model.Description;
             
                Data.Tickets.Add(ticket);

                var user = Data.ApplicationUser.All().FirstOrDefault(x => x.Id == userId);
                if (user != null)
                {
                    user.Points++;
                }
                
                Data.SaveChanges();
            }

            //model = new TicketViewModel();

            //model.CategoryItems = Data.Categories.All().ToList().Select(x => new SelectListItem()
            //{
            //    Value = x.Id.ToString(),
            //    Text = x.Name
            //}).ToList();

            //model.PriorityItems = Enum.GetValues(typeof(PriorityType)).Cast<PriorityType>().Select(v => new SelectListItem
            //{
            //    Text = v.ToString(),
            //    Value = ((int)v).ToString()
            //}).ToList();

            return RedirectToAction("Create");
        }

        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                RedirectToAction("Index", "Home");
            }

            var model = this.Data.Tickets.All()
                            .Where(x => x.Id == id.Value)
                            .Select(TicketDetailsVewModel.ToViewModel)
                            .FirstOrDefault();

            return View(model);
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult PostComment(SubmitCommentModel commentModel)
        {
            if (ModelState.IsValid)
            {
                var username = this.User.Identity.GetUserName();
                var userId = this.User.Identity.GetUserId();

                this.Data.Comments.Add(new Comment()
                {
                    AuthorId = userId,
                    Content = commentModel.Comment,
                    TicketId = commentModel.TicketId,
                });

                this.Data.SaveChanges();

                var viewModel = new CommentViewModel { AuthorName = username, Content = commentModel.Comment };
                return PartialView("_CommentPartial", viewModel);
            }

            return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest, ModelState.Values.First().ToString());
        }

        [Authorize]
        public JsonResult GetAllCategories()
        {
            var model = Data.Categories.All().Select(x=> new CategoryViewModel()
            {
                Id = x.Id,
                Name = x.Name
            });
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult Search(string categorySearch)
        {
            var result = this.Data.Tickets.All();

            if (!string.IsNullOrEmpty(categorySearch))
            {
                var categoryId = categorySearch.ToInt();
                result = result.Where(x => x.Category.Id.Equals(categoryId));
            }

            var endResult = result.Select(TicketsViewModel.ToViewModel);

            return View(endResult);
        }
	}
}

WebDevelopmentExams/AspNetMVC/Exam/Exam.Web/Views/Shared/_CommentPartial.cshtml
@model Exam.Web.Models.CommentViewModel
    <div><strong>@Model.AuthorName:</strong> @Model.Content</div>
<br/>

WebDevelopmentExams/AspNetMVC/Exam/Exam.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/unobrtrusive")
    @Styles.Render("~/Content/kendo")
    @Scripts.Render("~/bundles/kendo")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "brand" })
                <div class="nav-collapse collapse">
                    <ul class="nav" id="MainMenu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Available Tickets", "List", "Ticket")</li>
                            <li>@Html.ActionLink("Add Tickets", "Create", "Ticket")</li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                Administration
                                <ul>
                                    <li>@Html.ActionLink("Categories", "Index", "CategoryAdmin")</li>
                                    <li>@Html.ActionLink("Comments", "Index", "CommentAdmin")</li>
                                </ul>
                            </li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <h1>Ticket System</h1>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $("#MainMenu").kendoMenu();
    </script>
</body>
</html>